apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: platform
data:
  SERVICE_NAME: "notification-service"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PORT: "8009"
  JWT_PUBLIC_KEY_PATH: "/run/secrets/jwt/public_key.pem"
