"""initial schema: services health_check_records alerts

Revision ID: f19027bef573
Revises: 
Create Date: 2026-08-05 01:38:13.579885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19027bef573'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'HEALTHY', 'DEGRADED', 'DOWN', name='servicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('consecutive_failed_heartbeats', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('alerts',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity', native_enum=False, length=20), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus', native_enum=False, length=20), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_service_status', 'alerts', ['service_id', 'status'], unique=False)
    op.create_table('health_check_records',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_check_service_created', 'health_check_records', ['service_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_check_service_created', table_name='health_check_records')
    op.drop_table('health_check_records')
    op.drop_index('ix_alerts_service_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
