"""initial schema: log_analyses

Revision ID: e6a8644a2b56
Revises: 
Create Date: 2026-08-12 03:07:04.553659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a8644a2b56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_analyses',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('root_cause_summary', sa.Text(), nullable=False),
    sa.Column('human_explanation', sa.Text(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_analyses_service_id'), 'log_analyses', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_analyses_service_id'), table_name='log_analyses')
    op.drop_table('log_analyses')
    # ### end Alembic commands ###
