"""initial schema: metrics

Revision ID: 3d40b4d7f456
Revises: 
Create Date: 2026-08-05 01:47:53.332598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d40b4d7f456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('time', 'id')
    )
    op.create_index('ix_metrics_service_name_time', 'metrics', ['service_id', 'metric_name', 'time'], unique=False)
    # ### end Alembic commands ###

    # --- TimescaleDB hypertable conversion (graceful fallback) ---
    # WHY checked rather than attempted-and-caught: a failed statement
    # inside Alembic's transactional DDL would abort the whole migration,
    # not just this step. Checking `pg_available_extensions` first means
    # we only ever run CREATE EXTENSION / create_hypertable when they can
    # actually succeed — on plain Postgres (e.g. this project's CI/sandbox
    # environment) the table is created above as an ordinary, well-indexed
    # table and this block is a no-op; on the `timescale/timescaledb`
    # image used in infra/docker-compose.yml, it activates automatically.
    connection = op.get_bind()
    extension_available = connection.execute(
        sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb'")
    ).scalar()
    if extension_available:
        connection.execute(sa.text("CREATE EXTENSION IF NOT EXISTS timescaledb"))
        connection.execute(
            sa.text(
                "SELECT create_hypertable('metrics', 'time', if_not_exists => TRUE, migrate_data => TRUE)"
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_service_name_time', table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
