apiVersion: v1
kind: Service
metadata:
  name: k8s-management-service
  namespace: platform
  labels:
    app: k8s-management-service
spec:
  selector:
    app: k8s-management-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP
