apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-storage-service-config
  namespace: platform
data:
  SERVICE_NAME: "cloud-storage-service"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PORT: "8010"
  JWT_PUBLIC_KEY_PATH: "/run/secrets/jwt/public_key.pem"
