apiVersion: v1
kind: Service
metadata:
  name: cloud-storage-service
  namespace: platform
  labels:
    app: cloud-storage-service
spec:
  selector:
    app: cloud-storage-service
  ports:
    - port: 8010
      targetPort: 8010
  type: ClusterIP
