"""initial schema: scaling_history cluster_snapshots

Revision ID: 3e973567796c
Revises: 
Create Date: 2026-08-09 04:35:58.449146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e973567796c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('pod_count', sa.Integer(), nullable=False),
    sa.Column('pods_running', sa.Integer(), nullable=False),
    sa.Column('pods_pending', sa.Integer(), nullable=False),
    sa.Column('pods_failed', sa.Integer(), nullable=False),
    sa.Column('deployment_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_snapshots_time'), 'cluster_snapshots', ['time'], unique=False)
    op.create_table('scaling_history',
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('deployment_name', sa.String(length=150), nullable=False),
    sa.Column('from_replicas', sa.Integer(), nullable=False),
    sa.Column('to_replicas', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('trigger_source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scaling_history')
    op.drop_index(op.f('ix_cluster_snapshots_time'), table_name='cluster_snapshots')
    op.drop_table('cluster_snapshots')
    # ### end Alembic commands ###
