apiVersion: v1
kind: ConfigMap
metadata:
  name: predictive-maintenance-service-config
  namespace: ai
data:
  SERVICE_NAME: "predictive-maintenance-service"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PORT: "8007"
  JWT_PUBLIC_KEY_PATH: "/run/secrets/jwt/public_key.pem"
