apiVersion: v1
kind: Service
metadata:
  name: predictive-maintenance-service
  namespace: ai
  labels:
    app: predictive-maintenance-service
spec:
  selector:
    app: predictive-maintenance-service
  ports:
    - port: 8007
      targetPort: 8007
  type: ClusterIP
