apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth
data:
  SERVICE_NAME: "auth-service"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PORT: "8001"
  JWT_PUBLIC_KEY_PATH: "/run/secrets/jwt/public_key.pem"
