const $ = s => document.querySelector(s);
const content = $('#content');
let token = sessionStorage.getItem('helio_token');
let current = 'overview';
let cache = {};
const pageMeta = {overview:['COMMAND CENTER','Command center'],services:['OBSERVE / SERVICES','Services'],kubernetes:['OBSERVE / KUBERNETES','Kubernetes'],logs:['OBSERVE / LOG INTELLIGENCE','Log intelligence'],predict:['ANTICIPATE / PREDICTIVE OPS','Predictive ops'],costs:['GOVERN / CLOUD COST','Cloud cost and SLA'],storage:['GOVERN / CLOUD STORAGE','Cloud storage'],security:['GOVERN / IAM AND SECURITY','IAM and security'],network:['GOVERN / NETWORK','Cloud network'],resilience:['GOVERN / RESILIENCE','Disaster recovery'],settings:['MANAGE / WORKSPACE','Workspace']};

async function api(path, method='GET', body) {
  const res = await fetch(path,{method,signal:AbortSignal.timeout(10000),headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});
  const raw=await res.text(); let data={}; try{data=raw?JSON.parse(raw):{}}catch{throw new Error(`Server returned ${res.status}: ${raw.slice(0,90)}`)}
  if (!res.ok) throw new Error(data.detail || data.error || data.message || `Request failed (${res.status})`); return data;
}
const status = value => `<span class="status ${value}">${value}</span>`;
const esc = v => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function chart(values, forecast=false) { const max=Math.max(...values)*1.12, W=600,H=190, pad=8; const points=values.map((v,i)=>`${pad+i*(W-2*pad)/(values.length-1)},${H-pad-v/max*(H-25)}`).join(' '); return `<svg class="area-chart" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#b3f37d" stop-opacity=".22"/><stop offset="1" stop-color="#b3f37d" stop-opacity="0"/></linearGradient></defs><line class="grid" x1="0" y1="38" x2="600" y2="38"/><line class="grid" x1="0" y1="90" x2="600" y2="90"/><line class="grid" x1="0" y1="142" x2="600" y2="142"/><path class="area" d="M ${points} L ${W-pad},${H} L ${pad},${H} Z"/><polyline class="line" points="${points}"/>${forecast?`<line class="avg" x1="385" y1="0" x2="385" y2="190"/><text class="axis" x="390" y="16">FORECAST</text>`:''}<text class="axis" x="0" y="185">00:00</text><text class="axis" x="190" y="185">08:00</text><text class="axis" x="390" y="185">16:00</text><text class="axis" x="550" y="185">NOW</text></svg>` }
function intro(title, description, action='') { return `<div class="intro"><div><h1>${title}</h1><p>${description}</p></div>${action}</div>` }
function cardHead(title, aside='') { return `<div class="card-head"><h3>${title}</h3>${aside?`<small>${aside}</small>`:''}</div>` }
function toast(text) { const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200) }

async function renderOverview(){ const [o,a,s]=await Promise.all([api('/api/overview'),api('/api/alerts'),api('/api/services')]); const attention=s.services.filter(x=>x.status!=='healthy'); cache={o,a,s}; content.innerHTML=`${intro('Good morning, Anisha.','Here is the current shape of your production platform.','<button class="quiet-btn" onclick="navigate(\'services\')">View service catalog →</button>')}<div class="metric-grid"><div class="card metric"><label>PLATFORM HEALTH</label><strong class="health-number">${o.health}%</strong><small><b>+0.03%</b> compared to last 7 days</small></div><div class="card metric"><label>OPEN ALERTS</label><strong>${o.open_alerts}</strong><small><b>${a.alerts.filter(x=>x.severity==='critical').length} critical</b> requiring attention</small></div><div class="card metric"><label>REQUESTS · 24H</label><strong>${o.requests}</strong><small><b>${o.change}</b> against prior period</small></div><div class="card metric"><label>COMPUTE FLEET</label><strong>${o.nodes} <small>nodes</small></strong><small>146 pods across 3 regions</small></div></div><div class="dashboard-grid"><div class="card chart-card">${cardHead('Request throughput','LAST 24 HOURS')}<div class="chart-body"><div class="chart-keys"><span><i></i>requests / second</span><span><i class="dim"></i>baseline</span></div>${chart(o.traffic)}</div></div><div class="card">${cardHead('Regional health','UPTIME · 30D')}<div class="region-list">${o.regions.map((r,i)=>`<div class="region"><span>${r.name}</span><div class="bar"><i style="width:${93+i*3}%"></i></div><b>${r.value}%</b></div>`).join('')}</div><div class="kpi"><label class="card-label">INCIDENT RESPONSE</label><strong>4m 18s</strong><small class="sub">median acknowledge time</small></div></div></div><div class="page-grid"><div class="card table-card">${cardHead('Services needing attention',attention.length+' SIGNALS')}<table><thead><tr><th>SERVICE</th><th>STATUS</th><th>UPTIME</th><th>LATENCY</th><th></th></tr></thead><tbody>${attention.map(x=>`<tr><td><span class="service-name">${x.name}</span><span class="sub">${x.environment}</span></td><td>${status(x.status)}</td><td class="mono">${x.uptime}%</td><td class="mono">${x.latency}ms</td><td><button class="link-btn" onclick="navigate('services')">Inspect →</button></td></tr>`).join('')}</tbody></table></div><div class="card">${cardHead('Priority alerts','LIVE')}<div>${a.alerts.slice(0,3).map(x=>alertRow(x)).join('')}</div></div></div>` }
function alertRow(x){return `<div class="alert"><i class="sev ${x.severity}"></i><div><b>${esc(x.title)}</b><p>${esc(x.service)} · ${esc(x.detail)}</p><button class="link-btn" ${x.status==='acknowledged'?'disabled':''} onclick="ack(${x.id})">${x.status==='acknowledged'?'Acknowledged':'Acknowledge'}</button></div><time>${x.opened_at}</time></div>`}

async function renderServices(){ const d=await api('/api/services');cache.s=d;content.innerHTML=`${intro('Service catalog','Live health and performance of every registered workload.','<button class="quiet-btn" onclick="toast(\'Service registration opens in the production control plane.\')">+ Register service</button>')}<div class="card table-card"><table><thead><tr><th>SERVICE</th><th>ENVIRONMENT</th><th>TYPE</th><th>STATUS</th><th>UPTIME</th><th>THROUGHPUT</th><th>P95 LATENCY</th><th>LAST SIGNAL</th></tr></thead><tbody>${d.services.map(x=>`<tr><td><span class="service-name">${x.name}</span><span class="sub">${x.id}</span></td><td>${x.environment}</td><td class="mono">${x.kind}</td><td>${status(x.status)}</td><td class="mono">${x.uptime}%</td><td class="mono">${x.rps} r/s</td><td class="mono">${x.latency}ms</td><td class="sub">${x.last_seen}</td></tr>`).join('')}</tbody></table></div><div class="page-grid" style="margin-top:14px"><div class="card chart-card">${cardHead('Fleet latency','P95 · LAST 6 HOURS')}<div class="chart-body">${chart([31,34,39,36,42,40,46,53,51,59,55,63,67,62,72,81,77,69])}</div></div><div class="card"><div class="scale-card"><p class="card-label">SERVICE LEVEL OBJECTIVE</p><h3>Checkout request latency</h3><p>99.9% of requests should complete under 450ms. The current p95 is above the error budget threshold.</p><div class="bar"><i style="width:71%;background:var(--orange)"></i></div><p><b style="color:var(--orange)">71% budget consumed</b> in the current 30-day window.</p></div></div></div>`}

async function renderKubernetes(){const d=await api('/api/kubernetes');cache.k=d;content.innerHTML=`${intro('Kubernetes fleet','Cluster topology, workload readiness and controlled scaling.','<button class="quiet-btn" onclick="toast(\'Cluster context: core-production · us-east-1\')">core-production ⌄</button>')}<div class="page-grid"><div class="card"><div class="cluster-bar"><div class="cluster-stat"><label class="card-label">CLUSTER</label><strong>${d.cluster.name}</strong><small class="sub">${d.cluster.version} · 3 availability zones</small></div><div class="cluster-stat"><label class="card-label">CAPACITY</label><strong>${d.cluster.nodes} nodes</strong><small class="sub">${d.cluster.pods} running pods · ${d.cluster.deployments} deployments</small></div><div class="cluster-stat"><label class="card-label">CPU ALLOCATED</label><strong>${d.cluster.cpu}%</strong><div class="bar"><i style="width:${d.cluster.cpu}%"></i></div></div><div class="cluster-stat"><label class="card-label">MEMORY ALLOCATED</label><strong>${d.cluster.memory}%</strong><div class="bar"><i style="width:${d.cluster.memory}%;background:var(--yellow)"></i></div></div></div></div><div class="card"><div class="scale-card"><p class="card-label">CONTROLLED ACTION</p><h3>Scale a workload</h3><p>Every manual action is recorded in the audit trail. Production policies allow 1–40 replicas.</p><div class="scale-row"><select id="deployment">${d.deployments.map(x=>`<option>${x.name}</option>`).join('')}</select><input id="replicas" type="number" min="1" max="40" value="8"><button class="primary" onclick="scale()">Scale</button></div></div></div></div><div class="card table-card">${cardHead('Deployments','PRODUCTION NAMESPACE')}<table><thead><tr><th>WORKLOAD</th><th>READY</th><th>STATUS</th><th>CPU</th><th>REPLICAS</th></tr></thead><tbody>${d.deployments.map(x=>`<tr><td class="deploy-name">${x.name}<span class="sub">${x.namespace}</span></td><td class="mono">${x.ready}</td><td>${status(x.status)}</td><td><div class="progress ${x.cpu>75?'warn':''}"><i style="width:${x.cpu}%"></i></div><span class="sub mono">${x.cpu}%</span></td><td class="mono">${x.replicas}</td></tr>`).join('')}</tbody></table></div><div class="page-grid" style="margin-top:14px"><div class="card">${cardHead('Recent scaling history','AUDIT TRAIL')}<table><thead><tr><th>WORKLOAD</th><th>CHANGE</th><th>ACTOR</th><th>TIME</th></tr></thead><tbody>${d.actions.map(x=>`<tr><td>${x.deployment}<span class="sub">${x.namespace}</span></td><td class="mono">${x.previous_replicas} → ${x.replicas} replicas</td><td>${x.actor}</td><td class="sub">${x.created_at}</td></tr>`).join('')}</tbody></table></div><div class="card"><div class="scale-card"><p class="card-label">AUTOSCALER SIGNAL</p><h3>Checkout forecast recommends 8 replicas</h3><p>Predicted 268 req/s in the next 60 minutes with a 90% confidence interval of 232–301.</p><button class="quiet-btn" onclick="navigate('predict')">Review forecast →</button></div></div></div>`}

async function renderPredict(){const d=await api('/api/predictions');cache.p=d;const t=d.traffic;content.innerHTML=`${intro('Predictive operations','Forecast demand, make capacity decisions and prevent incidents before they arrive.')}<div class="page-grid"><div class="card forecast">${cardHead('Traffic forecast · checkout-api','NEXT 60 MINUTES')}<p class="big-number">${t.expected}<small> req / sec</small></p><p class="range">90% confidence range &nbsp; ${t.confidence[0]} — ${t.confidence[1]} req/s</p>${chart(t.points,true)}<div class="card" style="padding:13px;background:#132015;border-color:#375239"><span class="live-dot"></span> <b style="font-size:11px;margin-left:5px">Capacity recommendation: ${t.recommendation} replicas</b><span class="sub" style="margin-left:19px">Current state is ${t.current} replicas; add 2 before the projected peak.</span></div></div><div class="card"><div class="scale-card"><p class="card-label">FORECAST HEALTH</p><h3>Model is within expected accuracy</h3><p>The demand model continuously evaluates prior predictions against observed requests. Inputs include seasonality, API latency and observed CPU.</p><div class="kpi"><label class="card-label">LAST 7 DAYS · MAPE</label><strong>6.8%</strong><small class="sub">lower is better · target &lt; 10%</small></div><div class="kpi"><label class="card-label">DATA FRESHNESS</label><strong>1m 08s</strong><small class="sub">last metric ingestion</small></div></div></div></div><div class="card table-card" style="margin-top:14px">${cardHead('Predictive maintenance','FAILURE RISK · NEXT 24 HOURS')}<table><thead><tr><th>WORKLOAD</th><th>RISK</th><th>PRIMARY SIGNAL</th><th>RECOMMENDED RESPONSE</th></tr></thead><tbody>${d.maintenance.map(x=>`<tr><td class="service-name">${x.service}</td><td><span class="risk-score">${x.risk}%</span><div class="progress ${x.risk>50?'warn':''}" style="margin-top:5px"><i style="width:${x.risk}%"></i></div></td><td>${x.cause}</td><td>${x.recommendation}</td></tr>`).join('')}</tbody></table></div>`}

async function renderLogs(){const d=await api('/api/logs');cache.l=d;content.innerHTML=`${intro('Log intelligence','Search operational evidence and turn noisy events into an actionable diagnosis.','<button class="quiet-btn" onclick="toast(\'Streaming logs are current to the last 4 seconds.\')">● Streaming</button>')}<div class="log-layout"><div class="card"><div class="card-head"><h3>Live log stream</h3><small>PRODUCTION · ALL SERVICES</small></div><div class="logs">${d.entries.map(x=>`<div class="log"><span>${x.time}</span><span class="${x.level.toLowerCase()}">${x.level}</span><span class="service">${x.service}</span><span>${x.message}</span></div>`).join('')}</div></div><div class="card"><div class="ai-result"><span class="ai-tag">✦ AI INCIDENT ANALYST</span><h3>Ask about the evidence in your log stream.</h3><p>The analyzer combines logs, health checks and metric correlations. It identifies a likely cause; it does not execute changes.</p><textarea id="log-text" class="log-input textarea">checkout-api: timeout acquiring database connection from pool; p95 request duration above configured objective</textarea><button class="primary" style="width:100%" onclick="analyze()">Analyze signals <span>→</span></button><div id="analysis" class="empty">Awaiting an analysis request.</div></div></div></div>`}
function renderSettings(){content.innerHTML=`${intro('Workspace','Account context, permissions and platform guardrails.')}<div class="settings"><div class="card"><p class="card-label">IDENTITY & ACCESS</p><h3>Anisha Verma · Platform Operator</h3><p>Access is granted through production operator policy. Actions are authenticated and retained in the audit trail.</p><span class="chip">services:read</span><span class="chip">alerts:acknowledge</span><span class="chip">scaling:trigger</span><span class="chip">logs:analyze</span></div><div class="card"><p class="card-label">NOTIFICATION POLICY</p><h3>Production incident escalation</h3><p>Critical alerts notify the on-call owner immediately; unresolved alerts are escalated to the platform channel after 10 minutes. Deduplication window: 15 minutes.</p><button class="quiet-btn" onclick="toast('Policy changes require administrator approval.')">Manage policy</button></div><div class="card"><p class="card-label">DATA RETENTION</p><h3>Signals are retained by tier</h3><p>High-resolution metrics: 14 days · rollups: 13 months · audit data: 7 years. Export and deletion controls are available to workspace administrators.</p></div></div>`}
async function renderCosts(){const d=await api('/api/cloud/costs');const spend=Math.round(d.total/d.budget*100);content.innerHTML=`${intro('Cloud cost and SLA','FinOps visibility connects infrastructure decisions to cost, budget and service-level targets.')}<div class="metric-grid"><div class="card metric"><label>MONTHLY SPEND</label><strong>$${d.total}</strong><small>Budget: $${d.budget}</small></div><div class="card metric"><label>FORECAST</label><strong>$${d.forecast}</strong><small>${d.forecast>d.budget?'Budget attention required':'Within monthly budget'}</small></div><div class="card metric"><label>BUDGET USED</label><strong>${spend}%</strong><small>Cloud cost allocation</small></div><div class="card metric"><label>SLA TARGET</label><strong>99.9%</strong><small>RPO 15m · RTO 60m</small></div></div><div class="page-grid"><div class="card table-card">${cardHead('Cost allocation','CURRENT MONTH')}<table><thead><tr><th>SERVICE</th><th>OWNER</th><th>COST</th><th>CHANGE</th></tr></thead><tbody>${d.line_items.map(x=>`<tr><td>${esc(x.service)}</td><td>${esc(x.owner)}</td><td class="mono">$${x.cost}</td><td>${esc(x.change)}</td></tr>`).join('')}</tbody></table></div><div class="card"><p class="card-label">OPTIMIZATION</p><h3>Cost recommendations</h3>${d.recommendations.map(x=>`<p>• ${esc(x)}</p>`).join('')}<p class="sub">Data mode: ${esc(d.mode)} · refreshed ${esc(d.generated_at)}</p></div></div>`}
async function renderStorage(){const d=await api('/api/cloud/storage');content.innerHTML=`${intro('Cloud storage','Object storage, retention and encryption controls mapped to Cloud Storage-style buckets.')}<div class="page-grid"><div class="card">${cardHead('Buckets','ENCRYPTED AND VERSIONED')}<table><thead><tr><th>BUCKET</th><th>REGION</th><th>ENCRYPTION</th></tr></thead><tbody>${d.buckets.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.region)}</td><td>${esc(x.encryption)}</td></tr>`).join('')}</tbody></table></div><div class="card"><p class="card-label">REGISTER OBJECT</p><form id="storage-form" class="register-form"><label>Object name<input name="object_name" value="reports/platform-health.json" required></label><label>Storage class<select name="storage_class"><option>standard</option><option>nearline</option><option>coldline</option><option>archive</option></select></label><label>Retention days<input name="retention_days" type="number" min="1" value="90"></label><button class="primary">Register object <span>→</span></button><p class="error" id="storage-error"></p></form></div></div><div class="card table-card" style="margin-top:14px">${cardHead('Stored objects','DATA GOVERNANCE')}<table><thead><tr><th>OBJECT</th><th>BUCKET</th><th>CLASS</th><th>SIZE</th><th>ENCRYPTED</th><th>RETENTION</th></tr></thead><tbody>${d.objects.map(x=>`<tr><td>${esc(x.object_name)}</td><td>${esc(x.bucket)}</td><td>${esc(x.storage_class)}</td><td>${x.size_kb} KB</td><td>${x.encrypted?'Yes':'No'}</td><td>${x.retention_days} days</td></tr>`).join('')}</tbody></table></div>`;$('#storage-form').onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));values.retention_days=Number(values.retention_days);try{await api('/api/cloud/storage','POST',values);toast('Storage object registered and encrypted.');renderStorage()}catch(error){$('#storage-error').textContent=error.message}}}
async function renderSecurity(){const d=await api('/api/cloud/iam');content.innerHTML=`${intro('IAM and security','Least privilege, shared responsibility and verifiable controls for cloud operations.')}<div class="page-grid"><div class="card"><p class="card-label">SHARED RESPONSIBILITY</p><h3>Provider and customer responsibilities</h3><p><b>Cloud provider:</b> ${esc(d.shared_responsibility.provider)}</p><p><b>Platform team:</b> ${esc(d.shared_responsibility.customer)}</p></div><div class="card">${cardHead('Security controls','POLICY STATUS')}<div>${d.controls.map(x=>`<div class="alert"><i class="sev low"></i><div><b>${esc(x.name)}</b><p>${esc(x.status)}</p></div></div>`).join('')}</div></div></div><div class="card table-card" style="margin-top:14px">${cardHead('IAM roles','LEAST PRIVILEGE')}<table><thead><tr><th>ROLE</th><th>MEMBERS</th><th>PERMISSIONS</th></tr></thead><tbody>${d.roles.map(x=>`<tr><td>${esc(x.role)}</td><td>${x.members}</td><td>${esc(x.permissions.join(', '))}</td></tr>`).join('')}</tbody></table></div>`}
async function renderNetwork(){const d=await api('/api/cloud/network');content.innerHTML=`${intro('Cloud network','Reference VPC design showing isolated workloads, private data access and controlled ingress.')}<div class="card"><p class="card-label">VIRTUAL PRIVATE CLOUD</p><h3>${esc(d.vpc.name)} <span class="sub">${esc(d.vpc.cidr)} · ${esc(d.vpc.region)}</span></h3><div class="page-grid">${d.subnets.map(x=>`<div class="card"><p class="card-label">${esc(x.exposure).toUpperCase()} SUBNET</p><h3>${esc(x.name)}</h3><p class="mono">${esc(x.cidr)}</p><p>${esc(x.workloads)}</p></div>`).join('')}</div></div><div class="page-grid" style="margin-top:14px"><div class="card"><p class="card-label">TRAFFIC FLOW</p>${d.flows.map(x=>`<p>→ ${esc(x)}</p>`).join('')}</div><div class="card">${cardHead('Firewall policy','DEFAULT DENY')}<table><thead><tr><th>RULE</th><th>PORT</th><th>ACTION</th></tr></thead><tbody>${d.firewall_rules.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.ports)}</td><td>${esc(x.action)}</td></tr>`).join('')}</tbody></table></div></div>`}
async function renderResilience(){const d=await api('/api/cloud/resilience');content.innerHTML=`${intro('Disaster recovery','Recovery objectives, protected assets and a repeatable runbook for service continuity.')}<div class="metric-grid"><div class="card metric"><label>AVAILABILITY TARGET</label><strong>${d.targets.availability}</strong><small>Service level objective</small></div><div class="card metric"><label>RECOVERY TIME</label><strong>${d.targets.rto}</strong><small>RTO</small></div><div class="card metric"><label>RECOVERY POINT</label><strong>${d.targets.rpo}</strong><small>RPO</small></div><div class="card metric"><label>BACKUP HEALTH</label><strong>Healthy</strong><small>Last check: live demo</small></div></div><div class="page-grid"><div class="card table-card">${cardHead('Protected assets','BACKUP STATUS')}<table><thead><tr><th>ASSET</th><th>STRATEGY</th><th>LAST BACKUP</th><th>STATUS</th></tr></thead><tbody>${d.backups.map(x=>`<tr><td>${esc(x.asset)}</td><td>${esc(x.strategy)}</td><td>${esc(x.last_backup)}</td><td>${esc(x.status)}</td></tr>`).join('')}</tbody></table></div><div class="card"><p class="card-label">INCIDENT RUNBOOK</p><h3>Controlled recovery sequence</h3>${d.runbook.map((x,i)=>`<p>${i+1}. ${esc(x)}</p>`).join('')}</div></div>`}
const pages={overview:renderOverview,services:renderServices,kubernetes:renderKubernetes,predict:renderPredict,logs:renderLogs,costs:renderCosts,storage:renderStorage,security:renderSecurity,network:renderNetwork,resilience:renderResilience,settings:renderSettings};
async function navigate(page){current=page;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#crumb').textContent=pageMeta[page][0];$('#page-title').textContent=pageMeta[page][1];content.innerHTML='<div class="empty">Loading operational data…</div>';try{await pages[page]()}catch(e){content.innerHTML=`<div class="empty">Could not load this view: ${esc(e.message)}</div>`}document.querySelector('.sidebar').classList.remove('open')}
async function ack(id){try{await api(`/api/alerts/${id}/acknowledge`,'POST');toast('Alert acknowledged and added to audit trail.');navigate(current)}catch(e){toast(e.message)}}
async function scale(){try{const message=(await api('/api/kubernetes/scale','POST',{deployment:$('#deployment').value,replicas:$('#replicas').value})).message;toast(message);navigate('kubernetes')}catch(e){toast(e.message)}}
async function analyze(){const output=$('#analysis');output.className='empty';output.textContent='Correlating logs, metrics and alerts…';try{const d=await api('/api/logs/analyze','POST',{text:$('#log-text').value});output.className='ai-result';output.innerHTML=`<span class="ai-tag">${Math.round(d.confidence*100)}% CONFIDENCE · ${d.sources} CORRELATED SOURCES</span><h3>${esc(d.summary)}</h3><p>${esc(d.recommendation)}</p>`}catch(e){output.textContent=e.message}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';try{const d=await api('/api/auth/login','POST',{email:$('#email').value,password:$('#password').value});token=d.access_token;sessionStorage.setItem('helio_token',token);$('#login').hidden=true;$('#app').hidden=false;navigate('overview')}catch(e){$('#login-error').textContent=e.message}});
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$('#logout').addEventListener('click',()=>{sessionStorage.removeItem('helio_token');token=null;$('#app').hidden=true;$('#login').hidden=false});$('#mobile-menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
if(token){$('#login').hidden=true;$('#app').hidden=false;navigate('overview')}

function dialogShell(title){
  document.querySelector('#utility-dialog')?.remove();
  const el=document.createElement('div'); el.id='utility-dialog'; el.className='utility-backdrop';
  el.innerHTML=`<section class="utility-dialog" role="dialog" aria-modal="true"><div class="utility-head"><h3>${title}</h3><button class="icon-btn" id="utility-close" aria-label="Close">×</button></div><div id="utility-body"></div></section>`;
  document.body.append(el); el.querySelector('#utility-close').onclick=()=>el.remove(); el.onclick=e=>{if(e.target===el)el.remove()}; return el;
}
async function openNotifications(){
  const dialog=dialogShell('Notifications'); const body=dialog.querySelector('#utility-body'); body.innerHTML='<div class="empty">Loading notification activity…</div>';
  try { const [alertData, history]=await Promise.all([api('/api/alerts'),api('/api/v1/notifications')]);
    body.innerHTML=`<p class="utility-copy">Open incidents can be sent to the configured Slack escalation channel.</p><div class="utility-list">${alertData.alerts.filter(a=>a.status==='open').map(a=>`<article><b>${esc(a.title)}</b><span class="sub">${esc(a.service)} · ${esc(a.severity)}</span><button class="quiet-btn send-alert" data-alert="${esc(a.id)}">Send to Slack</button></article>`).join('') || '<div class="empty">No open alerts.</div>'}</div><p class="utility-label">RECENT DELIVERIES</p>${history.notifications.map(n=>`<div class="utility-history"><span>${esc(n.channel)}</span><span>${esc(n.status)}</span><small>${esc(n.sent_at)}</small></div>`).join('') || '<div class="empty">No notifications sent in this session.</div>'}`;
    body.querySelectorAll('.send-alert').forEach(button=>button.onclick=async()=>{try{await api('/api/v1/notifications/send','POST',{alert_id:button.dataset.alert,channel:'slack'}); toast('Notification sent to Slack.'); dialog.remove()}catch(e){toast(e.message)}});
  } catch(e) { body.innerHTML=`<div class="empty">Could not load notifications: ${esc(e.message)}</div>`; }
}
async function openSearch(){
  const dialog=dialogShell('Search platform'); const body=dialog.querySelector('#utility-body');
  body.innerHTML='<input id="platform-search" class="utility-input" placeholder="Search services, workloads, or alerts" autofocus><div id="search-results" class="utility-list"><div class="empty">Type to search the active platform inventory.</div></div>';
  const input=body.querySelector('#platform-search'), results=body.querySelector('#search-results'); let items=[];
  try { const [services, alerts]=await Promise.all([api('/api/services'),api('/api/alerts')]); items=[...services.services.map(s=>({title:s.name,detail:`Service · ${s.status} · ${s.environment}`,page:'services'})),...alerts.alerts.map(a=>({title:a.title,detail:`Alert · ${a.service} · ${a.severity}`,page:'overview'}))]; }
  catch(e){results.innerHTML=`<div class="empty">Search inventory is unavailable: ${esc(e.message)}</div>`; return;}
  input.oninput=()=>{const q=input.value.trim().toLowerCase(); const matches=items.filter(x=>!q||`${x.title} ${x.detail}`.toLowerCase().includes(q)); results.innerHTML=matches.length?matches.map(x=>`<button class="search-result" data-page="${x.page}"><b>${esc(x.title)}</b><span>${esc(x.detail)}</span></button>`).join(''):'<div class="empty">No matching services or alerts.</div>'; results.querySelectorAll('.search-result').forEach(b=>b.onclick=()=>{dialog.remove();navigate(b.dataset.page)})}; input.focus();
}
function applyAnishaIdentity(){
  document.querySelectorAll('.account b').forEach(el=>{if(el.textContent!=='Anisha Verma')el.textContent='Anisha Verma'});
  document.querySelectorAll('.avatar').forEach(el=>{if(el.textContent!=='AV')el.textContent='AV'});
  const greeting=document.querySelector('#content .intro h1'); const nextGreeting=`Good ${dayGreeting()}, Anisha.`; if(greeting?.textContent.startsWith('Good ')&&greeting.textContent!==nextGreeting)greeting.textContent=nextGreeting;
}
function dayGreeting(){const hour=new Date().getHours();return hour<12?'morning':hour<17?'afternoon':'evening'}
async function refreshNotificationBadge(){
  if(!token)return; try{const d=await api('/api/alerts');const count=d.alerts.filter(a=>a.status==='open').length;const badge=document.querySelector('.icon-btn[title="Notifications"] sup');if(badge)badge.textContent=count}catch(_){/* keep the last confirmed count */}
}
document.querySelector('.icon-btn[title="Notifications"]')?.addEventListener('click',openNotifications);
document.querySelector('.icon-btn[title="Search"]')?.addEventListener('click',openSearch);
const baseNavigate=navigate; navigate=async page=>{await baseNavigate(page);applyAnishaIdentity()}; setTimeout(applyAnishaIdentity,0);
// Navigation and the greeting timer update identity explicitly. Observing these
// same text changes would feed writes back into the observer and freeze the tab.
refreshNotificationBadge();
// A single completion-driven loop below owns background refreshes.
document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelector('#utility-dialog')?.remove();if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openSearch()}});
async function openRegisterService(){
  const dialog=dialogShell('Register service'); const body=dialog.querySelector('#utility-body');
  body.innerHTML=`<p class="utility-copy">Register a workload in the monitoring catalog. It appears immediately in Services and Search.</p><form id="service-registration" class="register-form"><label>Service name<input name="name" required pattern="[a-z][a-z0-9-]+" placeholder="payments-api"></label><label>Environment<select name="environment"><option value="production">Production</option><option value="staging">Staging</option><option value="development">Development</option></select></label><label>Workload type<select name="kind"><option value="api">API</option><option value="worker">Worker</option><option value="cron">Cron job</option></select></label><label>Namespace<input name="namespace" value="production" required></label><label>Owner team<input name="owner_team" value="platform" required></label><button class="primary" type="submit">Register service <span>→</span></button><p class="error" id="register-error"></p></form>`;
  body.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form.entries());try{await api('/api/services','POST',payload);toast(`${payload.name} registered successfully.`);dialog.remove();navigate('services')}catch(error){body.querySelector('#register-error').textContent=error.message}};
}
content.addEventListener('click',event=>{const button=event.target.closest('button');if(button?.textContent.trim()==='+ Register service'){event.preventDefault();event.stopPropagation();openRegisterService()}},true);

const advancedNav = document.querySelector('.sidebar nav');
advancedNav.insertAdjacentHTML('beforeend','<p>CLOUD GOVERNANCE</p><button class="nav" data-page="costs"><span>$</span> Cost and SLA</button><button class="nav" data-page="storage"><span>▣</span> Cloud storage</button><button class="nav" data-page="security"><span>◉</span> IAM and security</button><button class="nav" data-page="network"><span>⌘</span> Cloud network</button><button class="nav" data-page="resilience"><span>↺</span> Disaster recovery</button>');
advancedNav.querySelectorAll('[data-page="costs"],[data-page="storage"],[data-page="security"],[data-page="network"],[data-page="resilience"]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.page)));
async function refreshLiveStatus(){
  try {
    if(token && !document.hidden){
      applyAnishaIdentity();
      await refreshNotificationBadge();
      const live=await api('/api/live/telemetry');
      const badge=document.querySelector('.updated');
      const label=`Live demo · ${live.request_rate} r/s · ${live.latency_ms}ms`;
      if(badge && badge.textContent!==label)badge.textContent=label;
    }
  } catch(error){
    const badge=document.querySelector('.updated');
    if(badge)badge.textContent='Connection interrupted · retrying';
  } finally { setTimeout(refreshLiveStatus,10000); }
}
setTimeout(refreshLiveStatus,10000);
